# Generated by Django 4.2.5 on 2023-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsystemuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
