# Generated by Django 4.1 on 2023-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0002_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='license_plate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
