# Generated by Django 4.1 on 2023-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0003_parkingrecord_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_spots', models.PositiveIntegerField()),
                ('origin_parking_spots', models.PositiveIntegerField()),
            ],
        ),
    ]
